// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import multipart "mime/multipart"
import response "codeview/internal/dto/response"

// ImageService is an autogenerated mock type for the ImageService type
type ImageService struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, imageFileHeader
func (_m *ImageService) UploadImage(ctx context.Context, imageFileHeader *multipart.FileHeader) (*response.ImageResponse, error) {
	ret := _m.Called(ctx, imageFileHeader)

	var r0 *response.ImageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader) *response.ImageResponse); ok {
		r0 = rf(ctx, imageFileHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ImageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader) error); ok {
		r1 = rf(ctx, imageFileHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
