// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import pagination "codeview/internal/util/pagination"
import request "codeview/internal/dto/request"
import response "codeview/internal/dto/response"

// QuestionService is an autogenerated mock type for the QuestionService type
type QuestionService struct {
	mock.Mock
}

// CreateQuestion provides a mock function with given fields: ctx, req
func (_m *QuestionService) CreateQuestion(ctx context.Context, req *request.QuestionCreate) (*response.Question, error) {
	ret := _m.Called(ctx, req)

	var r0 *response.Question
	if rf, ok := ret.Get(0).(func(context.Context, *request.QuestionCreate) *response.Question); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *request.QuestionCreate) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteQuestionById provides a mock function with given fields: ctx, id
func (_m *QuestionService) DeleteQuestionById(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetQuestionById provides a mock function with given fields: ctx, id
func (_m *QuestionService) GetQuestionById(ctx context.Context, id uint) (*response.Question, error) {
	ret := _m.Called(ctx, id)

	var r0 *response.Question
	if rf, ok := ret.Get(0).(func(context.Context, uint) *response.Question); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestions provides a mock function with given fields: ctx, p
func (_m *QuestionService) GetQuestions(ctx context.Context, p *pagination.Pagination) ([]response.Question, error) {
	ret := _m.Called(ctx, p)

	var r0 []response.Question
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) []response.Question); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestionsByIds provides a mock function with given fields: ctx, ids, p
func (_m *QuestionService) GetQuestionsByIds(ctx context.Context, ids []uint, p *pagination.Pagination) ([]response.Question, error) {
	ret := _m.Called(ctx, ids, p)

	var r0 []response.Question
	if rf, ok := ret.Get(0).(func(context.Context, []uint, *pagination.Pagination) []response.Question); ok {
		r0 = rf(ctx, ids, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []uint, *pagination.Pagination) error); ok {
		r1 = rf(ctx, ids, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateQuestionById provides a mock function with given fields: ctx, id, body
func (_m *QuestionService) UpdateQuestionById(ctx context.Context, id uint, body *request.QuestionUpdate) (*response.Question, error) {
	ret := _m.Called(ctx, id, body)

	var r0 *response.Question
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.QuestionUpdate) *response.Question); ok {
		r0 = rf(ctx, id, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, *request.QuestionUpdate) error); ok {
		r1 = rf(ctx, id, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
