// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import pagination "codeview/internal/util/pagination"
import request "codeview/internal/dto/request"
import response "codeview/internal/dto/response"

// SourceService is an autogenerated mock type for the SourceService type
type SourceService struct {
	mock.Mock
}

// CreateSource provides a mock function with given fields: ctx, req
func (_m *SourceService) CreateSource(ctx context.Context, req *request.SourceCreate) (*response.Source, error) {
	ret := _m.Called(ctx, req)

	var r0 *response.Source
	if rf, ok := ret.Get(0).(func(context.Context, *request.SourceCreate) *response.Source); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *request.SourceCreate) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSourceById provides a mock function with given fields: ctx, id
func (_m *SourceService) DeleteSourceById(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSourceById provides a mock function with given fields: ctx, id
func (_m *SourceService) GetSourceById(ctx context.Context, id uint) (*response.Source, error) {
	ret := _m.Called(ctx, id)

	var r0 *response.Source
	if rf, ok := ret.Get(0).(func(context.Context, uint) *response.Source); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSources provides a mock function with given fields: ctx, p
func (_m *SourceService) GetSources(ctx context.Context, p *pagination.Pagination) ([]response.Source, error) {
	ret := _m.Called(ctx, p)

	var r0 []response.Source
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) []response.Source); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSourcesByIds provides a mock function with given fields: ctx, ids, p
func (_m *SourceService) GetSourcesByIds(ctx context.Context, ids []uint, p *pagination.Pagination) ([]response.Source, error) {
	ret := _m.Called(ctx, ids, p)

	var r0 []response.Source
	if rf, ok := ret.Get(0).(func(context.Context, []uint, *pagination.Pagination) []response.Source); ok {
		r0 = rf(ctx, ids, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []uint, *pagination.Pagination) error); ok {
		r1 = rf(ctx, ids, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSourceById provides a mock function with given fields: ctx, id, body
func (_m *SourceService) UpdateSourceById(ctx context.Context, id uint, body *request.SourceUpdate) (*response.Source, error) {
	ret := _m.Called(ctx, id, body)

	var r0 *response.Source
	if rf, ok := ret.Get(0).(func(context.Context, uint, *request.SourceUpdate) *response.Source); ok {
		r0 = rf(ctx, id, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Source)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, *request.SourceUpdate) error); ok {
		r1 = rf(ctx, id, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
