// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "codeview/internal/entity"
import mock "github.com/stretchr/testify/mock"
import multipart "mime/multipart"

// ImageRepository is an autogenerated mock type for the ImageRepository type
type ImageRepository struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: ctx, objName, imageFile
func (_m *ImageRepository) UploadImage(ctx context.Context, objName string, imageFile multipart.File) (*entity.Image, error) {
	ret := _m.Called(ctx, objName, imageFile)

	var r0 *entity.Image
	if rf, ok := ret.Get(0).(func(context.Context, string, multipart.File) *entity.Image); ok {
		r0 = rf(ctx, objName, imageFile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, multipart.File) error); ok {
		r1 = rf(ctx, objName, imageFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
