// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entity "codeview/internal/entity"
import mock "github.com/stretchr/testify/mock"
import pagination "codeview/internal/util/pagination"

// TagRepository is an autogenerated mock type for the TagRepository type
type TagRepository struct {
	mock.Mock
}

// CreateTag provides a mock function with given fields: ctx, body
func (_m *TagRepository) CreateTag(ctx context.Context, body *entity.Tag) (*entity.Tag, error) {
	ret := _m.Called(ctx, body)

	var r0 *entity.Tag
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Tag) *entity.Tag); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Tag) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTagById provides a mock function with given fields: ctx, id
func (_m *TagRepository) DeleteTagById(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTagById provides a mock function with given fields: ctx, id
func (_m *TagRepository) GetTagById(ctx context.Context, id uint) (*entity.Tag, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Tag
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.Tag); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTags provides a mock function with given fields: ctx, p
func (_m *TagRepository) GetTags(ctx context.Context, p *pagination.Pagination) ([]entity.Tag, error) {
	ret := _m.Called(ctx, p)

	var r0 []entity.Tag
	if rf, ok := ret.Get(0).(func(context.Context, *pagination.Pagination) []entity.Tag); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pagination.Pagination) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagsByIds provides a mock function with given fields: ctx, ids, p
func (_m *TagRepository) GetTagsByIds(ctx context.Context, ids []uint, p *pagination.Pagination) ([]entity.Tag, error) {
	ret := _m.Called(ctx, ids, p)

	var r0 []entity.Tag
	if rf, ok := ret.Get(0).(func(context.Context, []uint, *pagination.Pagination) []entity.Tag); ok {
		r0 = rf(ctx, ids, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []uint, *pagination.Pagination) error); ok {
		r1 = rf(ctx, ids, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTagById provides a mock function with given fields: ctx, id, body
func (_m *TagRepository) UpdateTagById(ctx context.Context, id uint, body *entity.Tag) (*entity.Tag, error) {
	ret := _m.Called(ctx, id, body)

	var r0 *entity.Tag
	if rf, ok := ret.Get(0).(func(context.Context, uint, *entity.Tag) *entity.Tag); ok {
		r0 = rf(ctx, id, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Tag)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, *entity.Tag) error); ok {
		r1 = rf(ctx, id, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
