CREATE TYPE tag_type AS ENUM ('NOTE', 'PROBLEM');

CREATE TABLE IF NOT EXISTS "tags" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "tag_type" tag_type NOT NULL DEFAULT 'PROBLEM',
  "label" VARCHAR(20) UNIQUE NOT NULL,
  "color" VARCHAR(7) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP DEFAULT NULL
);