CREATE TABLE IF NOT EXISTS "sources" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "label" VARCHAR(20) UNIQUE NOT NULL,
  "color" VARCHAR(7) NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP DEFAULT NULL
);